import enum


class Endpoint(str, enum.Enum):
    INDEX: str = "sky_index.html"
    WIRELESS_SETTINGS: str = "sky_wireless_settings.html"
    WIRELESS_BAND: str = "sky_wireless_band.cgi"
    WIRELESS_WPS: str = "sky_wireless_wps.html"
    ETHERNET: str = "sky_eth_setup.html"
    LOGS: str = "sky_logs.html"
    BLOCK_SITES: str = "sky_block_sites.html"
    FIREWALL_RULES: str = "sky_firewall_rules.html"
    SERVICES: str = "sky_services.html"
    SCHEDULE: str = "sky_schedule.html"
    ROUTER_STATUS: str = "sky_router_status.html"
    ATTACHED_DEVICES: str = "sky_attached_devices.html"
    BACKUP_SETTINGS: str = "sky_backup_settings.html"
    SET_PASSWORD: str = "sky_set_password.html"
    DIAGNOSTICS: str = "sky_diagnostics.html"
    ROUTER_UPGRADE: str = "sky_router_upgrade.html"
    WAN_SETUP: str = "sky_wan_setup.html"
    DYNAMIC_DNS: str = "sky_dynamic_dns.html"
    LAN_IP_SETUP: str = "sky_lan_ip_setup.html"
    REMOTE_MANAGEMENT: str = "sky_remote_management.html"
    UPNP: str = "sky_upnp.html"
    ALG: str = "sky_alg.html"
    SUPPORT: str = "sky_support.html"
    LICENSE: str = "sky_license.html"
    CONNECTION_STATUS: str = "sky_st_poe.html"
    SYSTEM: str = "sky_system.html"
