{
 "title": "SkyRouter",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "LAN", "type": "text", "gridPos": { "h": 1, "w": 10, "x": 2, "y": 0 } },
  { "title": "WAN", "type": "text", "gridPos": { "h": 1, "w": 12, "x": 12, "y": 0 } },
  {
   "title": "DOWNLOAD",
   "type": "barchart",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(received_bytes_per_second{port!=\"WAN\"})",
     "legendFormat": "Received"
    }
   ]
  },
  {
   "title": "RATE",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(received_bytes_per_second{port!=\"WAN\"})",
     "legendFormat": "DOWNLOAD"
    },
    {
     "expr": "sum(transmitted_bytes_per_second{port!=\"WAN\"})",
     "legendFormat": "UPLOAD"
    }
   ]
  },
  {
   "title": "RATE",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "received_bytes_per_second{port=\"WAN\"}",
     "legendFormat": "DOWNLOAD"
    },
    {
     "expr": "transmitted_bytes_per_second{port=\"WAN\"}",
     "legendFormat": "UPLOAD"
    }
   ]
  },
  {
   "title": "DOWNLOAD",
   "type": "barchart",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "received_bytes_per_second{port=\"WAN\"}",
     "legendFormat": "Received"
    }
   ]
  },
  {
   "title": "UPLOAD",
   "type": "barchart",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(transmitted_bytes_per_second{port!=\"WAN\"})",
     "legendFormat": "Transmitted"
    }
   ]
  },
  {
   "title": "UPLOAD",
   "type": "barchart",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "transmitted_bytes_per_second{port=\"WAN\"}",
     "legendFormat": "Transmitted"
    }
   ]
  },
  {
   "title": "PACKETS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(transmitted_packets{port!=\"WAN\"}[1m])",
     "legendFormat": "Transmitted"
    },
    {
     "expr": "rate(received_packets{port!=\"WAN\"}[1m])",
     "legendFormat": "Received"
    }
   ]
  },
  {
   "title": "PACKETS",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(transmitted_packets{port=\"WAN\"}[$__range])-min_over_time(transmitted_packets{port=\"WAN\"}[$__range])",
     "legendFormat": "Transmitted"
    },
    {
     "expr": "max_over_time(received_packets{port=\"WAN\"}[$__range])-min_over_time(received_packets{port=\"WAN\"}[$__range])",
     "legendFormat": "Received"
    }
   ]
  },
  {
   "title": "PACKETS",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(transmitted_packets{port=\"WAN\"}[$__range])-min_over_time(transmitted_packets{port=\"WAN\"}[$__range])",
     "legendFormat": "Transmitted"
    },
    {
     "expr": "max_over_time(received_packets{port=\"WAN\"}[$__range])-min_over_time(received_packets{port=\"WAN\"}[$__range])",
     "legendFormat": "Received"
    }
   ]
  },
  {
   "title": "Packets",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(transmitted_packets{port=\"WAN\"}[1m])",
     "legendFormat": "Transmitted"
    },
    {
     "expr": "rate(received_packets{port=\"WAN\"}[1m])",
     "legendFormat": "Received"
    }
   ]
  },
  {
   "title": "WAN",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 6, "x": 9, "y": 18 },
     "options": {
      "content": "<h1 style=\"font-size: 4em; text-align: center;\">WAN</h1>"
     }
    }
   ]
  },
  {
   "title": "Transmitted",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "AVERAGE",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 6, "x": 8, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg_over_time(received_bytes_per_second{port=\"WAN\"}[$__range])",
       "legendFormat": "DOWNLOAD"
      },
      {
       "expr": "avg_over_time(transmitted_bytes_per_second{port=\"WAN\"}[$__range])",
       "legendFormat": "UPLOAD"
      }
     ]
    },
    {
     "title": "Transmitted Data",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      { "expr": "transmitted_bytes_per_second" }
     ]
    },
    {
     "title": "Transmitted Packets",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "rate(transmitted_packets[1m])" }
     ]
    }
   ]
  },
  {
   "title": "Received",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Received Data",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      { "expr": "received_bytes_per_second" }
     ]
    },
    {
     "title": "Received Packets",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "rate(received_packets[1m])" }
     ]
    }
   ]
  }
 ]
}